#pragma once
enum op_type
{
	MULT, PLUS, MINUS, DIV, MOD, OR, AND, XOR, GOR, GAND, LESS, GREATER, EQUALS, COMMA, NEWLINE, WHILE, IF, NOT, PARENS, BRACKETS, BRACES, FUNC_CALL, VAR, NUMBER, LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, RETURN, ASSIGN, ID, SPACE, FUNC_DEF, NIL, NEG, VAL
};